### ISSUE TITLE
CI Storybook typescript typecheck step

### ISSUE THREAD

**Issue by DanielvanVliet** [Gemeente-DenHaag/denhaag-component-library#162]
We need a typescript typecheck step for storybook files in order to break the CI when a storybook file is incorrect.

The [Storybook Typescript documentation](https://storybook.js.org/docs/react/configure/typescript#mainjs-configuration) describes how to enable type checking.

### Tasks
- [ ] enable type checking in the storybook config
- [ ] enable eslint for storybook (also described in the linked doc)
- [ ] use correct tsconfig.json (the config where storybook resides)
- [ ] figured out the correct value for the `async` setting. It maybe worth while to set this to `false`.
- [ ] check if any other settings need to be enabled.
