### ISSUE TITLE
Fix installation files for components.

### ISSUE THREAD

**Issue by GewoonMaarten** [Gemeente-DenHaag/denhaag-component-library#42]
Currently, component's .tsx files are provided as is, meaning that the developer who installs the components gets the raw .tsx files. Usually you want to transpile the ts to js and provide a Typescript type file and/or transpile esx to es2017, which 90% of the browser support. This way developers can use both Javascript and Typescript.

TODO:
> According to [web.dev](https://web.dev/publish-modern-javascript/) the following package structure is desired when publishing a package. `modern.js` and `module.js` are es2017, while `legacy.cjs` is es5.
> ```json
> {
>   "name": "foo",
>   "exports": "./modern.js",
>   "main": "./legacy.cjs",
>   "module": "./module.js"
> }
> ```

**Tasks**
- [x] Research what files we want to provide to the user of the component
- [x] Fix the package such that these files are include in the package.
- [x] Test if the package is correctly installed.
- [x]  the microbundle-crl bundler does not install the Typescript types in the correct place (dist/src instead of dist).
- [x] components use react in their code, but don't have a dependency in their package.json. Add react as peer dependency.
