### ISSUE TITLE
Add an Icons Package

### ISSUE THREAD

**Issue by DanielvanVliet** [Gemeente-DenHaag/denhaag-component-library#46]
Currently we have no ideal solution for using Icons in the PWA.
One approach we use is to generate a React component from an svg.
This does not integrate with our other MUI-based components as nicely as it could.

MUI uses the SvgIcon component to create its icons. Using this in the PWA requires a dependency on MUI core and is not recommended.

If we expose an Icon package in the component library that uses SvgIcon internally we avoid alot of styling problems

**Tasks**
- [x] Add an icons package
- [x] Wrap the SvgIcon component
- [x] For each icon in the [design system](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=119%3A676), create an Icon Component.
- [x] Storybook stories to demonstrate how to use the icons (show all icons in one story/page)

**Acceptance criteria**
- [x] Components use SvgIcon
- [x] SvgIcon component can be used separately
- [x] All icons from the PWA prototype are supported

**Comment by bddjong** [comment]
This story has a lot of uncertainty:
- Do we provide all the icons in the component library (perhaps under an icons package), or do we simply export a generic SvgIcon component that allows end-users to implement their own icons
- Some of our components have an icon in them, such as the Card. Would a user importing our card component also get a whole load of icons they don't need? Or does the card itself include a single icon implementation, instead of relying on an entire Icons package
