### ISSUE TITLE
Make component library available for other projects

### ISSUE THREAD

**Issue by GewoonMaarten** [Gemeente-DenHaag/denhaag-component-library#5]
To enable developers to use our component library, it must be published on an NPM registry. 

This is also necessary for us to use the library in the PWA. We may want to initially publish the library on a private registry, but in the context of transparency and open-source it seems better to do this directly on NPM.

**Acceptance criteria**

* NDLS React Component Library packages are publicly available

* Packages are scoped (just like Material does with the @material). For example:
         `@nlds-react-components`
         `@nlds-react-components/input`
         `@nlds-react-components/layout`
         `@nlds-react-components/navigation`
         `@nlds-react-components/surfaces`

* The scope name has been determined in consultation with the Team (and possibly NLDS)

* The process of publishing new versions is clearly documented.
     * Is this automatic or is it done manually by maintainers?

**Tasks**

- [x] Package scope name has been determined
- [x] Component library can be used by 3rd party (decide how to do this)
- [x] Research publish workflow
- [x] Component library is available in NPM and can be used as a dependency in other projects

**Comment by Robbert** [comment]
@mjcarsjens The component library has been published once, are there any plans to publish to npm more frequently?
