### ISSUE TITLE
As a maintainer, I want a CLA and CLA bot to guarantee the open source license

### ISSUE THREAD

**Issue by GewoonMaarten** [Gemeente-DenHaag/denhaag-component-library#6]
* [CLA.md file](https://github.com/nl-design-system/web-component-poc/blob/main/CLA.md) (Contributor License Agreement) in the repository that must be signed to submit a pull request.

* Robbert Broersma (NLDS) in Slack, about their own POC repository: *Now when you contribute code via GitHub, you will automatically be asked to sign a Contributor License Agreement (CLA), so that the open source license is guaranteed for all code in the brand new Git repository. In any case, we have to set up that CLA bot for all repositories in the nl-design-system organization, so that the open source license is guaranteed. That is something I can help with.*

**Tasks**
- [x] Adopt NLDS CLA en modify for our project
- [x] Discuss with Jantien Hoving
- [ ] CLA bot requires signed CLA before merging a pull request
